#!/bin/sh

git clone https://github.com/NixOS/nixpkgs &&
( cd nixpkgs &&
  git remote add github git@github.com:ierton/nixpkgs.git &&
  git fetch github +local:local &&
  git checkout local
)

git clone https://github.com/NixOS/nixos &&
( cd nixos &&
  git remote add github git@github.com:ierton/nixos.git &&
  git fetch github +local:local &&
  git checkout local
)
