#!/bin/sh

git clone https://github.com/NixOS/nixpkgs &&
( cd nixpkgs && git fetch git@github.com:ierton/nixpkgs.git local ; )

git clone https://github.com/NixOS/nixos &&
( cd nixos && git fetch git@github.com:ierton/nixos.git local ; )
